### ISSUE TITLE
Aggregate shouldn't use a seed when it's not supplied

### ISSUE THREAD

**Issue by Igoorx** [xposure/Beef.Linq#7]
Currently if you use a class with the `Aggregate` function, there will always be a `null` in the first iteration of the `Aggregate` because of the seed even when you're not using a seed, this isn't how it is supposed to be, here is an example in C#:

With seed:
![image](https://user-images.githubusercontent.com/14041768/106068107-c9d33380-60de-11eb-8e49-803f7021c881.png)

Without seed:
![image](https://user-images.githubusercontent.com/14041768/106068132-d6578c00-60de-11eb-9643-1436fb100f98.png)

**Comment by xposure** [comment]
Should be fixed in 743a006
